### PR TITLE
Fix nav_bar_button class method

### LINKED ISSUE #666: nav_bar_button class method issue
The new `nav_bar_button` class method has a flaw in that it can only be used to set one nav bar button.

```ruby
class MyScreen < PM::Screen
  nav_bar_button :left, title: "Whatever", action: :my_action
  nav_bar_button :right, title: "Whatever2", action: :my_action2
```

In this case, only the second will be applied. We need to allow both, plus `nav_bar_buttons`.

Because of this, I won't advertise this new method in the 2.3 release notes.

### PR DESCRIPTION
**Pull request by jcarbo**
Fixes #666

Previously nav_bar_button would set an instance variable with the arguments for the last button added. This updates the nav_bar_button method to use an array to store the arguments so you can add multiple.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
If you accidentally do `left` and then `left` again, will it record two entries in the array?

**Comment by jcarbo** [comment]
It would put two entries into the array. When the screen is initialized it would call `set_nav_bar_button` which would initialize a new button for each set of arguments and set `leftBarButtonItem` each time. So the last one for each side would win.

How do you think this should be handled?
- I see there's a `set_nav_bar_buttons` so we could theoretically use that somehow to allow someone to use multiple buttons per side.
- We could just store these as a hash with `:left`, `:right`, `:back` keys instead of an array so setting multiple times still means the last one wins but we wouldn't be initializing an extra button.

I kinda think the second one makes more sense since it's probably the more common use-case, but defer to you guys. I can fix up the PR either way.

**Comment by markrickert** [comment]
ping @jamonholmgren

**Comment by jamonholmgren** [comment]
Oh, sorry about this @jcarbo . lgtm!

**Comment by jamonholmgren** [comment]
I'll release a new version of ProMotion within a week.

**Comment by markrickert** [comment]
`/slackbot remind me to release a new version of ProMotion in a week`

:smile:

**Comment by jamonholmgren** [comment]
screen shot 2016-03-07 at 5 08 55 pm

**Comment by jamonholmgren** [comment]
Released in 2.6.0: https://github.com/infinitered/ProMotion/releases/tag/v2.6.0

**Pull request merged**
