### PR TITLE
indent table cells when editing

### PR DESCRIPTION
**Pull request by kevinvangelder**

### CODE REVIEW

**Comment by carlinisaacson** [comment]
Have you confirmed that this works with custom cell classes? 

The issue I had seen before when working with @creationrose was that the default table cell that ProMotion uses does indent when editing but a custom cell does not.

**Comment by kevinvangelder** [comment]
@carlinisaacson Custom cells indent, but it appears that indenting is incompatible with constraints.

**Comment by jamonholmgren** [comment]
@kevinvangelder When you have tests I'll merge...thanks!

**Comment by jamonholmgren** [comment]
@carlinisaacson Next release maybe?

**Comment by jamonholmgren** [comment]
Oh wait, this is @kevinvangelder 's pr.

**Comment by markrickert** [comment]
ping @kevinvangelder

**Comment by kevinvangelder** [comment]
LOL, this was so long ago. I think I added it just because I saw it in Apple's documentation and I figured it would be easy enough to implement. Any tips on how I should try to detect if the cell is indented in my test?

**Comment by jamonholmgren** [comment]
No idea, Kev.

**Pull request closed without merging**
